version: 1.0.0.{build}
branches:
  only:
  - master
image:
- Visual Studio 2019
- Ubuntu1804
nuget:
  account_feed: true
  project_feed: true
build_script:
- pwsh: ./build.ps1
notifications:
- provider: Email
  to:
  - lokiphasma@gmail.com
  subject: A new version of NuGetDefense has successfullybeen built
  message: Build for NuGetDefense was successful
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: false
- provider: Email
  to:
  - lokiphasma@gmail.com
  subject: NuGetDefense Build Is Failing
  message: Look into the failure and create an issue if necessary.
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false