name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Initial Checkout
      uses: actions/checkout@v2.3.2
      with:
        path: ./NuGetDefense
        fetch-depth: 0

    - name: Checkout NVD Feed Impoorter
      uses: actions/checkout@v2.3.2
      with:
        repository: digitalcoyote/NuGetDefense.NVD
        path: ./NuGetDefense.NVD

    - name: Install dependencies
      run: | 
           dotnet nuget add source "https://nuget.pkg.github.com/digitalcoyote/index.json" --name github --username digitalcoyote --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
           dotnet restore ./NuGetDefense.NVD/Src/NuGetDefense.NVD.sln
           dotnet restore ./NuGetDefense/Src/NuGetDefense.sln
           dotnet tool install Nuke.GlobalTool --global
           dotnet tool install GitVersion.Tool --global


    - name: Generate VulnerabilityData.bin
      run: |
           dotnet build ./NuGetDefense.NVD/Src/NuGetDefense.NVD.sln -property:GeneratePackageOnBuild=false --configuration Release -v m
           mkdir -p ./NuGetDefense/Src/NuGetDefense/bin/Release/netcoreapp3.1
           dotnet ./NuGetDefense.NVD/Src/NVDFeedImporter/bin/Release/netcoreapp3.1/NVDFeedImporter.dll "./NuGetDefense/Src/NuGetDefense/bin/Release/netcoreapp3.1/"
      
    - name: Build NuGetDefense
      working-directory: NuGetDefense
      run: nuke --root ./
      
    - name: Test
      run: dotnet test ./NuGetDefense/Src/NuGetDefense.sln --no-restore --verbosity normal
      
    - name: Publish to GitHub Package Repository
      run: dotnet nuget push "./NuGetDefense/Src/NuGetDefense/bin/Release/*.nupkg" -s github
